- name: Emmanuel Noutahi
  email: emmanuel.noutahi@hotmail.ca
  aliases:
  - maclandrol
  num_commits: 17
  first_commit: 2020-10-25 10:15:22
- name: Hadrien Mary
  email: hadrien.mary@gmail.com
  aliases:
  - hadim
  alternate_emails:
  - hadim@users.noreply.github.com
  num_commits: 368
  first_commit: 2020-10-24 11:46:22
- name: michelml
  email: michmoreau.l@gmail.com
  num_commits: 6
  first_commit: 2021-02-25 15:48:52
- name: Honoré Hounwanou
  email: mercuryseries@gmail.com
  num_commits: 1
  first_commit: 2021-02-12 17:01:32
- name: Therence1
  email: 38595485+Therence1@users.noreply.github.com
  num_commits: 3
  first_commit: 2021-04-03 17:31:09
- name: mike
  email: michael@invivoai.com
  num_commits: 3
  first_commit: 2021-03-30 16:03:51
