- name: Emmanuel Noutahi
  email: emmanuel.noutahi@hotmail.ca
  aliases:
  - maclandrol
  num_commits: 5
  first_commit: 2020-10-25 10:15:22
- name: Hadrien Mary
  email: hadrien.mary@gmail.com
  aliases:
  - hadim
  alternate_emails:
  - hadim@users.noreply.github.com
  num_commits: 67
  first_commit: 2020-10-24 11:46:22
