site_name: "datamol"
site_description: "A python library to work with molecules. Built on top of rdkit."
site_url: "https://github.com/invivoai-platform/datamol"
repo_url: "https://github.com/invivoai-platform/datamol"
repo_name: "invivoai-platform/datamol"
copyright: Copyright 2020 - 2021 InvivoAI

remote_branch: "privpage"
use_directory_urls: false
docs_dir: "docs"

nav:
  - Overview: index.md
  - Usage: usage.md
  - Examples:
      - The Basics: examples/The_Basics.ipynb
      - Preprocessing Molecules: examples/Preprocessing_Molecules.ipynb
      - Cluster Molecules: examples/Cluster_Molecules.ipynb
      - Fragment and Scaffold: examples/Fragment_and_Scaffold.ipynb
  - API:
      - datamol: api/datamol.md
      - datamol.actions: api/datamol.actions.md
      - datamol.conformers: api/datamol.conformers.md
      - datamol.fragment: api/datamol.fragment.md
      - datamol.reactions: api/datamol.reactions.md
      - datamol.scaffold: api/datamol.scaffold.md
      - datamol.utils: api/datamol.utils.md
      - datamol.viz: api/datamol.viz.md
  - License: license.md

theme:
  name: material
  palette:
    primary: teal
    accent: purple
  features:
    - navigation.instant
    - navigation.expand

extra_css:
  - _assets/css/custom.css

markdown_extensions:
  - admonition
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("docs")
            - sys.path.append("datamol")
          selection:
            new_path_syntax: yes
          rendering:
            show_root_heading: yes
            heading_level: 3
  - mkdocs-jupyter:
      execute: False

extra:
  # Unused at the moment, waiting for `mkdocstrings`
  # to release it.
  version:
    method: mike
