site_name: "datamol"
site_description: "A python library to work with molecules. Built on top of rdkit."
site_url: "https://github.com/invivoai-platform/datamol"
repo_url: "https://github.com/invivoai-platform/datamol"
repo_name: "invivoai-platform/datamol"
copyright: Copyright 2020 - 2021 InvivoAI

docs_dir: "docs"

nav:
  - Overview: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Examples:
      - The Basics: examples/The_Basics.ipynb
      - Preprocessing Molecules: examples/Preprocessing_Molecules.ipynb
      - Cluster Molecules: examples/Cluster_Molecules.ipynb
      - Fragment and Scaffold: examples/Fragment_and_Scaffold.ipynb
  - API:
      - datamol.mol: api/datamol.mol.md
      - datamol.fragment: api/datamol.fragment.md
      - datamol.actions: api/datamol.actions.md
      - datamol.cluster: api/datamol.cluster.md
      - datamol.convert: api/datamol.convert.md
      - datamol.data: api/datamol.data.md
      - datamol.fp: api/datamol.fp.md
      - datamol.graph: api/datamol.graph.md
      - datamol.io: api/datamol.io.md
      - datamol.log: api/datamol.log.md
      - datamol.reactions: api/datamol.reactions.md
      - datamol.scaffold: api/datamol.scaffold.md
      - datamol.similarity: api/datamol.similarity.md
      - datamol.utils: api/datamol.utils.md
      - datamol.viz: api/datamol.viz.md

  - License: license.md

theme:
  name: material
  custom_dir: docs/_theme
  # favicon: assets/img/favicon.png
  # logo: assets/img/icon.png
  palette:
    primary: teal
    accent: purple

extra_css:
  - _assets/css/mkautodoc.css

markdown_extensions:
  - admonition
  - mkautodoc
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: "¤"

plugins:
  - search
  - mkapi:
      src_dirs: [datamol]
  - mkdocs-jupyter:
      execute: False
