name: doc

on:
  push:
    branches: ["master"]
    tags: ["*"]

jobs:
  doc:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 3
        with:
          path: ~/conda_pkgs_dir
          key: conda-${{ runner.os }}-${{ env.CACHE_NUMBER }}-${{ hashFiles('env.yml') }}

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          use-mamba: true
          use-only-tar-bz2: true
          auto-activate-base: true
          activate-environment: ""

      - name: Install Dependencies
        run: |
          mamba create -n datamol
          conda activate datamol
          mamba env update -f env.yml

      - name: Install library
        run: |
          conda activate datamol
          python -m pip install .

      - name: Deploy the doc
        run: |
          conda activate datamol

          # Get the gh-pages branch
          git fetch origin gh-pages

          # Regenerate the API doc
          python -m datamol._mkdocs

          if [ $GITHUB_REF = "master" ]; then
            mike deploy --push master
          else
            # Make default doc
            mike set-default stable
            mike deploy --push stable
            mike deploy --push $GITHUB_REF
          fi
