name: Install, test and release the library

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "*"
      - "!privpage"

jobs:
  build-install-and-test:
    name: Build, install and test the library
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 1
        with:
          path: ~/conda_pkgs_dir
          key: conda-${{ runner.os }}-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}

      - name: Setup conda
        uses: goanpeca/setup-miniconda@v1
        with:
          channels: conda-forge
          activate-environment: app-env
          mamba-version: "*"
          use-only-tar-bz2: true # requried for caching

      - name: List dependencies
        shell: bash -l {0}
        run: |
          mamba env update -f env.yml
          mamba list

      - name: Install library
        shell: bash -l {0}
        run: |
          mamba env list
          python -m pip install .

      - name: Run tests
        shell: bash -l {0}
        run: |
          pytest -v tests/

      - name: Test building the doc
        shell: bash -l {0}
        run: |
          # Regenerate the API doc
          python -m datamol._mkdocs

          # Build and serve the doc
          mkdocs build

      - name: Deploy the doc
        if: ${{ github.ref == 'refs/heads/master' }}
        shell: bash -l {0}
        run: |
          # Get the privpage branch
          git fetch origin privpage

          # Regenerate the API doc
          python -m datamol._mkdocs

          # Build and serve the doc
          mkdocs gh-deploy
