name: Test

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "*"
      - "!privpage"

jobs:
  test:
    name: Test

    strategy:
      fail-fast: false
      matrix:
        # os: ["ubuntu", "macos", "windows"]
        os: ["ubuntu"]
        # python-version: [3.6, 3.7, 3.8, 3.9]
        python-version: [3.8, 3.9]
        rdkit-version: [2020.09]
        # include:
        #   - os: ubuntu
        #     miniforge-variant: Mambaforge
        #     bash-cmd: bash -l {0}
        #   - os: macos
        #     miniforge-variant: Mambaforge
        #     bash-cmd: bash -l {0}
        #   - os: windows
        #     miniforge-variant: Mambaforge
        #     bash-cmd: cmd /C call {0}

    runs-on: ${{ matrix.os }}-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 3
        with:
          path: ~/conda_pkgs_dir
          key: conda-${{ runner.os }}-${{ env.CACHE_NUMBER }}-${{ hashFiles('env.yml') }}

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@master # TODO: pin the version when new version is released.
        with:
          miniforge-variant: Mambaforge
          use-mamba: true
          use-only-tar-bz2: true
          python-version: 3.8
          auto-activate-base: true
          activate-environment: ""

      - name: Install Dependencies
        run: |
          # Patch the conda env file
          python .github/patch_conda_env.py --env env.yml -d \
            python=${{ matrix.python-version }} \
            rdkit=${{ matrix.rdkit-version }} \
            > env-patched.yml

          # Display the new env file
          cat env-patched.yml

          conda create -n datamol
          conda activate datamol

          # Install the deps
          mamba env update -f env-patched.yml

      - name: Install library
        run: python -m pip install .

      - name: Run tests
        run: pytest -v .

      - name: Test building the doc
        run: |
          # Regenerate the API doc
          python -m datamol._mkdocs

          # Build and serve the doc
          mkdocs build

      - name: Deploy the doc
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          # Get the privpage branch
          git fetch origin privpage

          # Regenerate the API doc
          python -m datamol._mkdocs

          # Build and serve the doc
          mkdocs gh-deploy
